---

- name: install packages
  become: yes
  yum:
    name:
      - bzip2-devel
      - gdbm-devel
      - libffi-devel
      - libuuid-devel
      - ncurses-devel
      - openssl-devel
      - readline-devel
      - sqlite-devel
      - tk-devel
      - wget
      - xz-devel
      - zlib-devel
      - python3
      - python3-devel
      - python3-pip
  tags:
    - python
