---
- name: Configure apt
  become: true
  ansible.builtin.replace:
    dest: /etc/apt/sources.list
    regexp: 'http://(.*\.)?archive\.ubuntu\.com/ubuntu/'
    replace: "http://jp.archive.ubuntu.com/ubuntu/"
  tags:
    - setup

- name: Upgrade packages # noqa package-latest
  become: true
  ansible.builtin.apt:
    state: latest
    update_cache: true
    name: "*"
  tags:
    - setup

- name: Upgrade dist packages
  become: true
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
    cache_valid_time: 3600
  tags:
    - setup
